In [1]:
import numpy as np

In [ ]:
#FONTOS!!!

# CSAK OTT LEHET HASZNÁLNI FOR LOOP-OT AHOL A FELADAT KÜLÖN KÉRI!
# [1,2,3,4] --> ezek az értékek np.array-ek. Ahol listát kérek paraméterként ott külön ki fogom emelni!
# Ha végeztél a feladatokkal, akkor notebook-ot alakítsd át .py.
# A FÁJLBAN CSAK A FÜGGVÉNYEK LEGYENEK! (KOMMENTEK MARADHATNAK)

In [44]:
#Készíts egy függvényt ami létre hoz egy nullákkal teli numpy array-t.
#Paraméterei: mérete (tuple-ként), default mérete pedig legyen egy (2,2)
#Be: (2,2)
#Ki: [[0,0],[0,0]]
#create_array()

[[0, 0], [0, 0]]

In [43]:
def create_array(size=(2,2)):
    return np.zeros(size, dtype=int).tolist()

In [42]:
#Készíts egy függvényt ami a paraméterként kapott array-t főátlóját feltölti egyesekkel
#Be: [[1,2],[3,4]]
#Ki: [[1,2],[3,1]]
#set_one(arr)

In [41]:
def set_one(arr = np.array([[1,2],[3,4]])):
  return np.fill_diagonal(arr, 1)

In [24]:
# Készíts egy függvényt ami transzponálja a paraméterül kapott mártix-ot:
# Be: [[1, 2], [3, 4]]
# Ki: [[1, 3], [2, 4]]
# do_transpose(a)

array([[1, 3],
       [2, 4]])

In [23]:
def do_transpose(arr):
  return np.transpose(arr)

In [31]:
# Készíts egy olyan függvényt ami az array-ben lévő értékeket N tizenedjegyik kerekíti, ha nincs megadva ez a paraméter, akkor legyen az alapértelmezett a kettő 
# Be: [0.1223, 0.1675], 2
# Ki: [0.12, 0.17]
# round_array(a, 2)

array([0.12, 0.17])

In [30]:
def round_array(a = np.array([0.1223, 0.1675]), n = 2):
  return np.around(a, n)

In [33]:
# Készíts egy olyan függvényt, ami a bementként kapott 0 és 1 ből álló tömben a 0 - False-ra, az 1 True-ra cserélni
# Be: [[1, 0, 0], [1, 1, 1],[0, 0, 0]]
# Ki: [[ True False False], [ True  True  True], [False False False]]
# bool_array()

array([[ True, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [32]:
def bool_array(a = np.array([[1, 0, 0], [1, 1, 1],[0, 0, 0]])):
  return a!=0

In [36]:
# Készíts egy olyan függvényt, ami a bementként kapott 0 és 1 ből álló tömben a 1 - False-ra az 0 True-ra cserélni
# Be: [[1, 0, 0], [1, 1, 1],[0, 0, 0]]
# Ki: [[ False True True], [ False  False  False], [True True True]]
# invert_bool_array()

array([[ True, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [35]:
def invert_bool_array(a = np.array([[1, 0, 0], [1, 1, 1],[0, 0, 0]])):
  return a!=0

In [40]:
# Készíts egy olyan függvényt ami a paraméterként kapott array-t kilapítja
# Be: [[1,2], [3,4]]
# Ki: [1,2,3,4]
# flatten()


array([1, 2, 3, 4])

In [39]:
def flatten(a = np.array([[1,2], [3,4]])):
  return a.flatten()